### ISSUE TITLE
DEPOPTS missing in autoappveyor output

### ISSUE THREAD

**Issue by kit-ty-kate** [yomimono/autoci#11]
When I'm trying to translate an existing ```.travis.yml``` file to appveyor using ```travis_to_appveyor``` there is something weird happening with the DEPOPTS variables.
In the travis file the line looks like this:
```
- PACKAGE="containers" OCAML_VERSION="4.06.0" DEPOPTS="base-threads base-unix"
```
but once translated to appveyor I get:
```
- OPAM_SWITCH: 4.06.0+mingw64c
  PACKAGE: containers
  DEPOPTS: ! '"base-threads base-unix"] '
```
I don't know the right syntax for that but something tells me it's probably not this one.

**Comment by yomimono** [comment]
I noticed this too and pushed https://github.com/yomimono/autoci/commit/f14aa74f9bfab78a7ce74a5519c3e15ccf944ed0 to try to fix it last week - do you have that commit?

**Comment by jpdeplaix** [comment]
Arf no. Sorry for the noise :/

Mmh also, is it normal that autoappveyor does not give any DEPOPTS variables ?

**Comment by yomimono** [comment]
Does the `opam` have depopts?

**Comment by jpdeplaix** [comment]
yes and autotravis gives the DEPOPTS

**Comment by yomimono** [comment]
:bug:

**Comment by yomimono** [comment]
https://github.com/yomimono/autoci/commit/17ccdba0f89058de32434b0e8f812907da25bf45 has fixes and tests for this, thanks for reporting it!
