### ISSUE TITLE
Change 'lint' executable name.

### ISSUE THREAD

**Issue by Drup** [yomimono/autoci#13]
`lint` is a far too generic command name.

I think you should have a multi-command tool. It would do `autoci travis`, `autoci lint`, etc.

**Comment by yomimono** [comment]
OK, I'll do that.  Thanks!

**Comment by samoht** [comment]
+1 for the multi-command tool

**Comment by yomimono** [comment]
https://github.com/yomimono/autoci/commit/1589c7064dc9d3010a99cad58f7ace87843d308b grants wishes!
