### ISSUE TITLE
default distro maybe shouldn't be ubuntu

### ISSUE THREAD

**Issue by yomimono** [yomimono/autoci#9]
I chose ubuntu because it has (AFAICT) the biggest set of populated `depext`s and therefore had the highest chance to Just Work and not introduce problems out of scope for the package maintainer (e.g., I depend on package `foo` which depends on package `bar` which depends on `conf-baz` which isn't available for alpine).  But perhaps the depext universe for alpine is populated enough for this not to be a problem - some data on this would be helpful in making the right decision.

**Comment by avsm** [comment]
The opam-ci's default distro is debian-stable. Perhaps the same default here, rather than Ubuntu?

**Comment by yomimono** [comment]
That's as good an argument as any, so as of https://github.com/yomimono/autoci/commit/493e1dd1576f2705587a9b76dd1eb950cb58fc15 we'll use `debian-stable`.
